on:
  pull_request:
    branches: [ pipeLineBranch ]

jobs:
  build:
    runs-on: uduntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 19
        uses: actions/setup-java@v2
        with:
          java version: '19'
          distrobution: 'adopt'