on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: uduntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 19
        uses: actions/setup-java@v2
        with:
          java-version: '19'
          distrobution: 'adopt'

test:
  needs: [build]
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - name: Set up JDK19
      uses: actions/checkout@v2
      with:
        java-version: 19
        distorbution: 'adopt'

    - name: Build with maven
      run: mvn -B clean test